# fly.toml app configuration file generated for personal-website-late-bird-5083 on 2024-08-31T14:56:50-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-website-late-bird-5083'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
